version: '3.4'

services:
  app:
    image: brunocasas/siga-base
    env_file:
      - ./.env
    volumes:
      - ./data/props/default.properties:/opt/jboss/siga/default.properties
      - ./data/configs:/opt/jboss/siga/configs
      - ./data/deployments:/opt/jboss/siga/deployments
    networks:
      - traefik-public
      - siga-network
    deploy:
      labels:
        # General
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        # Wildfly root redirect
        - "traefik.http.routers.wl.service=siga"
        - "traefik.http.routers.wl.entrypoints=web"
        - "traefik.http.routers.wl.rule=Path(`/`)"
        - "traefik.http.routers.wl.middlewares=wl-rerirect"
        - "traefik.http.middlewares.wl-rerirect.redirectregex.regex=^http:\\/\\/([^\\/]+)\\/?$$"
        - "traefik.http.middlewares.wl-rerirect.redirectregex.replacement=http://$$1/siga"
        # Siga config
        - "traefik.http.routers.siga.entrypoints=web"
        - "traefik.http.routers.siga.service=siga"
        - "traefik.http.routers.siga.rule=PathPrefix(`/siga`)"
        - "traefik.http.services.siga.loadbalancer.server.port=8080"
        - "traefik.http.services.siga.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.siga.loadBalancer.sticky.cookie.name=siga-sticky"
      restart_policy:
        condition: on-failure

#  db:
#    image: mysql:8.0.25
#    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
#    volumes:
#      - "./data/mysql:/var/lib/mysql"
#    environment:
#      MYSQL_ROOT_PASSWORD: SigaAdmin
#    networks:
#      - siga-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    networks:
      - siga-network

  # nginx:
  #   build: ./services/nginx
  #   networks:
  #     - siga-desenv
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - app

  viz:
    image: omerio/graphviz-server
    command: "8080"
    networks:
      - siga-network

  bluc:
    image: brunocasas/blucservice
#    volumes:
#      - ./logs/bluc:/var/log
    networks:
      - siga-network

  assijus:
    image: brunocasas/assijus
    volumes:
      - ./logs/assijus:/var/log
    environment:
      PROP_ASSIJUS_REDIS_MASTER_HOST: redis
      PROP_ASSIJUS_REDIS_MASTER_PORT: 6379
      PROP_ASSIJUS_REDIS_SLAVE_HOST:
      PROP_ASSIJUS_REDIS_SLAVE_PORT:
      PROP_ASSIJUS_REDIS_PASSWORD: sigadesenv
      PROP_ASSIJUS_REDIS_DATABASE: 1
      PROP_ASSIJUS_BLUCSERVICE_URL: http://bluc:8080/blucservice/api/v1
      PROP_ASSIJUS_POPUP_URLS: http://localhost:8080
      PROP_ASSIJUS_SYSTEMS: testsigner
      PROP_ASSIJUS_TESTSIGNER_URL: http://testsigner:8080/testsigner/api/v1
      PROP_ASSIJUS_TESTSIGNER_PASSWORD: sigadesenvteste
      # PROP_ASSIJUS_TIMESTAMP_PUBLIC_KEY:
      # PROP_ASSIJUS_TIMESTAMP_PRIVATE_KEY:
    networks:
      - siga-network

  redis:
    image: redis
    command: redis-server --requirepass sigadesenv
    networks:
      - siga-network

networks:
  traefik-public:
    external: true
  siga-network:
