version: '3.4'

services:
  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: SigaAdmin
    networks:
      - siga-network
