version: '3.8'

services:
  app:
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.http.routers.siga-${SIGA_SERVICE_POSTFIX-default}.entrypoints=${ENTRY:?Ponto de entrada não definido}"
  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    volumes:
      - ../../data/siga-${SIGA_SERVICE_POSTFIX-default}/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SigaAdmin
      MYSQL_USER: siga
      MYSQL_PASSWORD: siga
      TZ: America/Cuiaba
    networks:
      - siga-network
    configs:
      - source: db_config
        target: /docker-entrypoint-initdb.d/db_siga_grant.sql

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost/admin/database
    networks:
      - siga-network
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin.entrypoints=${ENTRY:?Ponto de entrada não definido}"
        - "traefik.http.routers.siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin.service=siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin"
        - "traefik.http.routers.siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin.rule=PathPrefix(`/admin/database/`)"
        - "traefik.http.routers.siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin.middlewares=siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin-stripprefix"
        - "traefik.http.middlewares.siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin-stripprefix.stripprefix.prefixes=/admin/database"
        - "traefik.http.services.siga-${SIGA_SERVICE_POSTFIX-default}-dbadmin.loadbalancer.server.port=80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - siga-network

  assijus:
    deploy:
      labels:
        - "traefik.http.routers.assijus-${SIGA_SERVICE_POSTFIX-default}.rule=PathPrefix(`/assijus`)"

configs:
  db_config:
    file: ./configs/db_siga_grant.sql
