version: '3.4'

services:
  traefik:
    command:
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsresolver.acme.email=${TRAEFIK_ACME_EMAIL:?Email do acme não definido em TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsresolver.acme.storage=/traefik/acme.json"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    volumes:
      - "../../data/infra/traefik:/traefik"
    ports:
      - target: 443
        published: 443
        mode: host
    deploy:
      labels:
        # Global http redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
        # Traefik http redirect router
        - "traefik.http.routers.traefik-http.entrypoints=web"
        - "traefik.http.routers.traefik-http.rule=PathPrefix(`/`)"
        - "traefik.http.routers.traefik-http.middlewares=redirect-to-https"
        # Traefik main router
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.rule=Host(`${INFRA_HOST:?Host de infra não foi definido em INFRA_HOST}`) && (PathPrefix(`/admin/traefik/`) || PathPrefix(`/api`))"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=letsresolver"
