version: '3.8'

services:
  traefik:
    deploy:
      labels:
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.rule=PathPrefix(`/admin/traefik`) || PathPrefix(`/api`)"