version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.useBindPortIP=true"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.test.address=:8181"
      - "--entrypoints.jmx.address=:20200"
      - "--entrypoints.rmi.address=:20300"
      #- --accesslog
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8181
        published: 8080
        mode: host
      - target: 20200
        published: 20200
        mode: host
      - target: 20300
        published: 20300
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=888"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/admin/traefik"
        - "traefik.http.middlewares.traefik-basicauth.basicauth.users=${TRAEFIK_AUTH:?Basic auth não definido em TRAEFIK_AUTH}"
        - "traefik.http.routers.traefik.middlewares=traefik-basicauth,traefik-stripprefix"
        
networks:
  traefik-public:
    external: true